/**
 * Generates a simple UUID-like identifier without dependencies
 * This is more reliable than the previous implementation
 */
export function generateSimpleUuid(): string {
  // Get current timestamp in milliseconds (for uniqueness)
  const timestamp = new Date().getTime().toString(36)

  // Add random components for additional uniqueness
  const randomA = Math.random().toString(36).substring(2, 10)
  const randomB = Math.random().toString(36).substring(2, 6)
  const randomC = Math.random().toString(36).substring(2, 6)

  // Combine parts in a UUID-like format
  return `${timestamp}-${randomA}-${randomB}-${randomC}`
}

/**
 * Validates if a string looks like a UUID generated by our function
 */
export function isValidUuid(id: string): boolean {
  // Simple validation - check if it has the expected format with hyphens
  const parts = id.split("-")
  return parts.length === 4 && id.length >= 20
}
